### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by IanYangChina** [xinyiz0931/bin-picking-robot#2]
Hi Xinyi,

This is Xintong from Cardiff University.
I'm trying to incorporate your work with my own manipulation project.
I wonder if you can provide the camera intrinsic and extrinsic you used when taking the example depth images?

Thanks a lot!

**Comment by xinyiz0931** [comment]
Hi Xintong, 
I use a already calibrated depth sensor, and the extrinsic matrix is a 4x4 matrix recorded in `./data/calibration/calibmat.txt`.

**Comment by IanYangChina** [comment]
Hi Xinyi,
Thanks for the reply! I found that extrinsic matrix.
May I ask for the intrinsic parameters as well?

**Comment by xinyiz0931** [comment]
Hi Xintong, 
(1) I only did robot-camera calibration for extrinsic matrix. As for intrinsic parameters, I only use the default matrix from the sensor. I don't know where it is... 
(2) I manually define the max distance and min distance (in `./cfg/config.yaml`), and normalized the depth image between pixel values 0~255.

**Comment by IanYangChina** [comment]
Thank you very much! Great works!
