### ISSUE TITLE
Insufficient number of returned grasps in detect_grasp.

### ISSUE THREAD

**Issue by Naoki04** [xinyiz0931/bin-picking-robot#3]
Hi Xinyi Zhang,

Thank you for your code. I found that the function "detect_grasp" returned less than expected grasps. For example, even when I set n_grasp=5, the function returns 3 grasps. This problem seems to come from a bug in the function "grasp_ranking" in "bin-picking-robot/bpbot/grasping/graspability.py".

I think the condition in the while loop should be k<n, not I<n.

`
 def grasp_ranking(self, candidates, w, h, n=10, _dismiss=50, _distance=50):

        """
        Detect grasp with graspability
        Arguments:
            candidates {list} -- a list of grasps candidates
            w {int} -- width
            h {int} -- height

        Keyword Arguments:
            n {int} -- number of grasp (default: {20})
            _dismiss {int} -- distance that will not collide with the box (default: {25})

        Returns:
            [array] -- an array of sorted grasps [[x,y,r (degree)], ...]
        """
        # candidates.sort(key=self.takefirst, reverse=True)
        i = 0
        k = 0
        grasps = []
        # print("Computing grasps! ")
        if len(candidates) < n:
            n = len(candidates)
        while (len(candidates) and k < n and i<len(candidates)): # not i<n but k<n edited by Naoki
            x = candidates[i][1]
            y = candidates[i][2]
            ## consider dismiss/distance to rank grasp candidates
`

**Comment by xinyiz0931** [comment]
Thank you very much! I revised it.
